/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#dfe8ff",
        "primary-container": "#0066cc",
        "surface-bright": "#fcf8fb",
        "tertiary-container": "#67686c",
        "on-primary": "#ffffff",
        "primary": "#004e9f",
        "error-container": "#ffdad6",
        "outline-variant": "#c1c6d5",
        "secondary-fixed": "#e2e2e4",
        "surface-container-high": "#eae7ea",
        "outline": "#727784",
        "secondary-container": "#dfdfe1",
        "on-surface": "#1b1b1d",
        "on-primary-fixed-variant": "#00458e",
        "inverse-on-surface": "#f3f0f2",
        "tertiary-fixed": "#e2e2e7",
        "surface-dim": "#dcd9dc",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1a1c1d",
        "primary-fixed": "#d7e3ff",
        "on-tertiary": "#ffffff",
        "secondary": "#5d5e60",
        "surface-container-low": "#f6f3f5",
        "surface": "#fcf8fb",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#aac7ff",
        "surface-tint": "#005cba",
        "on-surface-variant": "#414753",
        "tertiary": "#4e5054",
        "on-tertiary-fixed": "#1a1c1f",
        "surface-container-highest": "#e4e2e4",
        "on-tertiary-container": "#e8e8ed",
        "background": "#fcf8fb",
        "surface-variant": "#e4e2e4",
        "inverse-surface": "#303032",
        "error": "#ba1a1a",
        "on-primary-fixed": "#001b3e",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c6c6cb",
        "inverse-primary": "#aac7ff",
        "on-tertiary-fixed-variant": "#45474b",
        "on-background": "#1b1b1d",
        "on-secondary-container": "#616365",
        "surface-container": "#f0edef",
        "on-secondary-fixed-variant": "#454749",
        "secondary-fixed-dim": "#c6c6c8"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-page": "48px",
        "container-max": "1200px",
        "section-padding": "80px",
        "unit": "8px",
        "gutter": "24px"
      },
      "fontFamily": {
        "headline-md": ["Geist", "sans-serif"],
        "subhead-caps": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "subhead-caps": ["12px", { "lineHeight": "1.5", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "display": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-sm": ["13px", { "lineHeight": "1.4", "letterSpacing": "0em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
